// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcbwtxaiqzpeylrfgvhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjYnd0eGFpcXpwZXlscmZndmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODIyMzQsImV4cCI6MjA2OTY1ODIzNH0._oSxPNQl5rJXSWk8Jt9U8nlDAAACtPaxueMuBB-r6I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});